default: &default
  adapter: postgresql
  encoding: unicode
  user: panoptes
  password: panoptes
  host: postgres 
  pool: 5
  port: 5432

development:
  <<: *default
  database: panoptes_development

test:
  <<: *default
  database: panoptes_test